### ISSUE TITLE
Geopandas and Zonal Statistic error

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [perrygeo/python-rasterstats#110]
I run this code
```
import geopandas as gpd
from rasterstats import zonal_stats

geodf = gpd.read_file("SHP/shape.shp")
zonal_stats(geodf,"raster.tif")
```
but I get this error:
```
ParseException: Unknown type: 'FID'
ParseException: Unexpected EOF parsing WKB
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2820, in run_code
exec code_obj in self.user_global_ns, self.user_ns
File "<ipython-input-43-3d15c4dddd4f>", line 1, in <module>
zonal_stats(geodf,"raster.tif",stats='mean')
File "/usr/local/lib/python2.7/dist-packages/rasterstats/main.py", line 21, in zonal_stats
return list(gen_zonal_stats(*args, **kwargs))
File "/usr/local/lib/python2.7/dist-packages/rasterstats/main.py", line 128, in gen_zonal_stats
for i, feat in enumerate(features_iter):
File "/usr/local/lib/python2.7/dist-packages/rasterstats/io.py", line 107, in <genexpr>
features_iter = (parse_feature(x) for x in obj)
File "/usr/local/lib/python2.7/dist-packages/rasterstats/io.py", line 70, in parse_feature
raise ValueError("Can't parse %s as a geojson Feature object" % obj)
ValueError: Can't parse FID as a geojson Feature object
```
The data frame looks like this:
```
In[43]: geodf
Out[42]: 
     FID                                      geometry

0     0  POLYGON ((7.662965420348624 45.05600185397847,...
1     1  POLYGON ((7.665210146514162 45.05607590098681,...
2     2  POLYGON ((7.663353281768154 45.05601113630467,...
3     3  POLYGON ((7.660229137844505 45.0570570693801, ...
4     4  POLYGON ((7.660047499767138 45.0572381357898, ...
....
```
Any suggestion how to solve this problem?

**Comment by perrygeo** [comment]
Thanks for the bug report. I will look into it this weekend.

What version of rasterstats, geopandas and pandas are you using?

**Comment by perrygeo** [comment]
I can confirm that this is occurring on the latest master. The geopandas test was not sufficient to catch this error so I will make a proper test and get this working shortly.

**Comment by perrygeo** [comment]
@LorenzoBottaccioli Thanks for the bug report! This should be fixed now in master, I'll make a point release shortly with the fix.

**Comment by LorenzoBottaccioli** [comment]
Welcome! @perrygeo Can you please let me know when the bug will be fixed or how to fix it by my own?
Thanks

**Comment by perrygeo** [comment]
@LorenzoBottaccioli upgrading to version 0.10.2 should fix the issue. `pip install -U rasterstats` (or pull the latest git master if installing from source)

**Comment by LorenzoBottaccioli** [comment]
@perrygeo upgraded to version 0.10.2. Download the zip file from git hub and installed with `sudo python setup.py install` but the error persist.

**Comment by LorenzoBottaccioli** [comment]
@perrygeo I'm usign `geopands v 0.1.1` `pandas v 0.13.1` `rasterstats v 0.10.2` `fiona 1.6.3` `rasterio 0.31.0` and `numpy 1.8.2`

**Comment by perrygeo** [comment]
I cannot reproduce the error. Please try the following in your console and let me know what you see (all of the data is in this repo at `tests/data/`)

```
>>> import geopandas as gpd
>>> from rasterstats import zonal_stats
>>> gdf = gpd.read_file("tests/data/polygons.shp")
>>> zonal_stats(gdf, 'tests/data/slope.tif')
[{'count': 75,
  'max': 22.273418426513672,
  'mean': 14.660084635416666,
  'min': 6.575114727020264},
 {'count': 50,
  'max': 82.69043731689453,
  'mean': 56.60576171875,
  'min': 16.940950393676758}]

>>> import rasterstats
>>> rasterstats.__version__
'0.10.2'
```

If the above works but your data does *not*, then it is a separate issue and I'll need your help in providing code and test datasets to reproduce it. Thanks!

**Comment by LorenzoBottaccioli** [comment]
@perrygeo This is what i get:
```
import geopandas as gpd
from rasterstats import zonal_stats
gdf = gpd.read_file("tests/data/polygons.shp")
zonal_stats(gdf, 'tests/data/slope.tif')`

ParseException: Unknown type: 'GEOMETRY'
ParseException: Unexpected EOF parsing WKB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/rasterstats/main.py", line 21, in zonal_stats
  File "build/bdist.linux-x86_64/egg/rasterstats/main.py", line 128, in gen_zonal_stats
  File "build/bdist.linux-x86_64/egg/rasterstats/io.py", line 113, in <genexpr>
  File "build/bdist.linux-x86_64/egg/rasterstats/io.py", line 70, in parse_feature
    __metaclass__ = abc.ABCMeta
ValueError: Can't parse geometry as a geojson Feature object

import rasterstats
rasterstats.__version__
'0.10.2'
 ```

**Comment by perrygeo** [comment]
OK, I've confirmed that error by installing geoapandas verson `0.1.1`. The issue has been resolved in geopandas master branch for over a year but unfortunately that project has not made an official release since 2014. 

Until we get a new geopandas release, the solution is to install geopandas from the master branch
```
git clone git@github.com:geopandas/geopandas.git
cd geopandas/
pip install -e .
```

**Comment by LorenzoBottaccioli** [comment]
@perrygeo Ok now it works. Just one last thing..why i don't get the `__fid__` in results of `zonal_stats(gdf, 'tests/data/slope.tif')`?

**Comment by perrygeo** [comment]
the `__fid__` was dropped in 0.9 since it was redundant (the ith dictionary in the the returned list is just `fid == i`). You can use `enumerate()` if you need the index or `geojson_out` if you need feature attributes.

**Comment by perrygeo** [comment]
@LorenzoBottaccioli and thanks for working with me through this bug report. hopefully we'll get new geopandas release shortly!

**Comment by mhasanbd08** [comment]
Dear all,
Greetings!
I have tried several time to work with rasterstats from install to execution but not working showing error "not found module gd" during execution. Please help me. thanks advance
